### ISSUE TITLE
VnV: abstractness of the SRS verification plan 

### ISSUE THREAD

**Issue by shmouses** [XingzhiMac/CAS741-Proj#18] opened 2020-11-07 23:05 UTC
Dear Xiangzhi,
I believe your SRS verification plan can be more systematic and be more organized. For instance, you can define better review cycles and add peer feedback into your plan. You can also be more specific with assigning tasks by naming each VnV team member and mentioning what they are supposed to do.

![image](https://user-images.githubusercontent.com/49411064/98453109-6eb72380-2123-11eb-8358-53cab22d3cb5.png)

**Comment by XingzhiMac** [comment] 2020-12-23 14:40
Thanks for your comment! The issue is addressed in 98a2667

**Closed by XingzhiMac** 2020-12-23 14:40 UTC
