### ISSUE TITLE
VnV: Abstractness of implementation verification plan

### ISSUE THREAD

**Issue by shmouses** [XingzhiMac/CAS741-Proj#19] opened 2020-11-07 23:28 UTC
Dear Xiangzhi,
I believe the implementation verification plan similar to the SRS verification plan can be more organized and by assigning specific tasks to your VnV team members it can be more clear. I also think at the end of the paragraph you talk about the automated testing which can be moved to the next section.

![image](https://user-images.githubusercontent.com/49411064/98453224-d6ba3980-2124-11eb-86a7-5499a6d82659.png)

**Comment by XingzhiMac** [comment] 2020-12-23 14:39
Thanks for your comment! The issue is addressed in 98a2667.

**Closed by XingzhiMac** 2020-12-23 14:39 UTC
